name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.18.1'

    - name: Cache Yarn
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Set up Python and MSVS
      run: |
        set PYTHON=C:\hostedtoolcache\windows\Python\3.9.0\x64\python.exe
        set GYP_MSVS_VERSION=2022

    - name: Fix OpenSSL Issue
      run: |
        set npm_config_openssl_no_asm=true

    - name: Install Yarn
      run: npm install -g yarn && yarn config set ignore-engines true

    - name: Clear Cache and Reinstall
      run: |
        npm cache clean --force
        yarn cache clean
        rm -rf node_modules yarn.lock
        yarn install --frozen-lockfile

    - name: Run build script
      run: .\build.bat

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*.exe
