name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.18.1'

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Visual Studio Build Tools
      run: npm install -g windows-build-tools@5.2.2
      shell: pwsh

    - name: Set up node-gyp environment
      run: |
        npm config set python "$(which python)"
        npm config set msvs_version 2019
      shell: bash

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Force node-gyp rebuild
      run: yarn rebuild --arch=x64
      shell: bash

    - name: Run build script
      run: .\build.bat

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*.exe
